### ISSUE TITLE
Fix grammar usage in index.html file

### ISSUE THREAD

**Issue by therealharish** [iamshreyashh/Attendence_proximator1.github.io#1]
Original Line: https://github.com/iamshreyashh/Attendence_proximator1.github.io/blob/3c9734525913dd96e2883fcfff6eb3531a583ca1/index.html#L49

The text "Check how much lectures you can bunk!!" in the index.html file should be changed to "Check how many lectures you can bunk!!" to address correct grammar usage.

This change improves the clarity and correctness of the message displayed on the website.

Please consider making this modification to enhance the overall quality of the project.

**Comment by iamshreyashh** [comment]
Okay Harish, thanks for letting me know.
